#!/usr/bin/env bash

#MISE description="Edit a sops encrypted secrets file"
#USAGE arg "<file>" help="The secrets file to edit" default=".creds.env.yaml"

#MISE raw=true

sops "$MISE_ORIGINAL_CWD/${usage_file:?}"
