#!/usr/bin/env bash

#MISE description="Show decrypted contents of a sops encrypted secrets file"
#USAGE arg "<file>" help="The secrets file to show" default=".creds.env.yaml"

sops --decrypt "$MISE_ORIGINAL_CWD/${usage_file:?}"
