[tools]
age = "latest"
atuin = "latest"
bat = "latest"
eza = "latest"
fzf = "latest"
gum = "latest"
jq = "latest"
python = "3.12"
node = "lts"
pnpm = "latest"
sops = "latest"
starship = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
usage = "2.11"
restic = "latest"
gitleaks = "latest"
pre-commit = "latest"
kubectl = "1.34.3"
kubectx = "latest"
kubens = "latest"
helm = "4.0.4"
kustomize = "5.8.0"
flux2 = "2.7.5"
kubeconform = "0.7.0"
k9s = "latest"
github-cli = "latest"
glab = { version = "latest", exe = "glab" }
vault = "latest"

[settings]
experimental = true

[env]
SOPS_AGE_RECIPIENTS = "age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/mise/age.txt"
