brews:
  - name: zsh
  - name: wget
  - name: stow
  - name: git
  - name: thefuck
  - name: dos2unix
  - name: figlet
  - name: bfg
  - name: orbstack
    cask: true
  - name: controlplaneio-fluxcd/tap/flux-operator-mcp
  - name: controlplaneio-fluxcd/tap/flux-operator
  - name: gnupg
  - name: watch
  - name: cloud-provider-kind
custom:
  - runbook
  - bash-commons
  - pocketbase
  - mani
  - teller
mise:
  - age
  - atuin
  - bat
  - eza
  - fzf
  - gum
  - jq
  - python@3.12
  - node@lts
  - pnpm
  - sops
  - starship
  - yq
  - zellij
  - zoxide
  - usage@2.11
  - restic
  - gitleaks
  - pre-commit
  - kubectl@1.34.3
  - kubectx
  - kubens
  - helm@4.0.4
  - kustomize@5.8.0
  - flux2@2.7.5
  - kubeconform@0.7.0
  - k9s
  - github-cli
  - glab
npm:
  - oclif
  - "@fission-ai/openspec@latest"
stows:
  - atuin
  - zsh
  - git
  - mise
  - starship
  - zellij
  - neofetch
  - claude
  - notes
